spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev    #开发环境
  applcation: 
    name: springcloud-config-bwei-dev
---
spring:
  profiles: test    #测试环境
  applcation: 
    name: springcloud-config-bwei-test